[package]
name = "sui-token-gen-rpc"
version = "0.16.0"
rust-version = "1.70.0"
authors = []
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/sui-token-gen-rpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "network", "server", "microservices", "example"]
categories = ["asynchronous", "network-programming"]
readme = "README.md"
description = "A server application built using Tarpc, designed for token generation and verification with RPC and REST capabilities."

[dependencies]
anyhow = "1.0"
async-trait = "0.1.83"
axum = { version = "0.7", features = ["json"] }
chrono = "0.4.38"
clap = { version = "4.4.18", features = ["derive"] }
dotenv = { version = "0.15" }
envy = "0.4.2"
futures = "0.3"
git2 = "0.17"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
inquire = "=0.0.7"
log = "0.4"
once_cell = "1.20.2"
openssl = { version = "0.10", features = ["vendored"] }
opentelemetry = { version = "0.26.0" }
opentelemetry-otlp = "0.26.0"
opentelemetry-semantic-conventions = "0.16.0"
opentelemetry_sdk = { version = "0.26.0", features = ["rt-tokio"] }
rand = "0.8.5"
regex = "1.11.1"
reqwest = "0.12.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tarpc = { version = "0.35", features = ["full"] }
tera = "1.20"
thiserror = "2.0.4"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
toml = "0.8.19"
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
tower_governor = "0.5.0"
tracing = { version = "0.1" }
tracing-opentelemetry = "0.27.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.4"

[lib]
name = "service"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/tests/client/mod.rs"
